spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/bookorders
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.fake-region.amazonaws.com/fake-pool
server:
  port: 8080
